# Generated by Django 3.2.25 on 2024-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/images/default_profile2_q4xt5g', upload_to='images/'),
        ),
    ]
